config/routes.rb
Bocwd::Application.routes.draw do
  resources :developers

  get "home/index"
  root :to => "home#index"

end

app/models/developer.rb
class Developer < ActiveRecord::Base
  attr_accessible :name, :website

  validates :name,  :presence => true
  validates :website, :presence => true
                   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  # GET /developers
  # GET /developers.json
  def index
    @developers = Developer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @developers }
    end
  end

  # GET /developers/1
  # GET /developers/1.json
  def show
    @developer = Developer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @developer }
    end
  end

  # GET /developers/new
  # GET /developers/new.json
  def new
    @developer = Developer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @developer }
    end
  end

  # GET /developers/1/edit
  def edit
    @developer = Developer.find(params[:id])
  end

  # POST /developers
  # POST /developers.json
  def create
    @developer = Developer.new(params[:developer])

    respond_to do |format|
      if @developer.save
        format.html { redirect_to @developer, notice: 'Developer was successfully created.' }
        format.json { render json: @developer, status: :created, location: @developer }
      else
        format.html { render action: "new" }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /developers/1
  # PUT /developers/1.json
  def update
    @developer = Developer.find(params[:id])

    respond_to do |format|
      if @developer.update_attributes(params[:developer])
        format.html { redirect_to @developer, notice: 'Developer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1
  # DELETE /developers/1.json
  def destroy
    @developer = Developer.find(params[:id])
    @developer.destroy

    respond_to do |format|
      format.html { redirect_to developers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/developers/_form.html.erb
<%= form_for(@developer) do |f| %>
  <% if @developer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
      <% @developer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/developers/edit.html.erb
<h1>Editing developer</h1>

<%= render 'form' %>

<%= link_to 'Show', @developer %> |
<%= link_to 'Back', developers_path %>

app/views/developers/index.html.erb
<h1>Listing developers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @developers.each do |developer| %>
  <tr>
    <td><%= developer.name %></td>
    <td><%= developer.website %></td>
    <td><%= link_to 'Show', developer %></td>
    <td><%= link_to 'Edit', edit_developer_path(developer) %></td>
    <td><%= link_to 'Destroy', developer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Developer', new_developer_path %>

app/views/developers/new.html.erb
<h1>New developer</h1>

<%= render 'form' %>

<%= link_to 'Back', developers_path %>

app/views/developers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @developer.name %>
</p>

<p>
  <b>Website:</b>
  <%= @developer.website %>
</p>


<%= link_to 'Edit', edit_developer_path(@developer) %> |
<%= link_to 'Back', developers_path %>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>

<%= link_to "Orange County Internet Makers", developers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bocwd</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>